### ISSUE TITLE
[Mac OS X] Insufficient privileges to run the program even when in the Applications folder

### ISSUE THREAD

**Issue by ghost** [arkOScloud/arkos-install#11]
On the Mac OS X  I've built the distributable with py2app. When I try to execute it outside of the Applications folder it tells that I don't have sufficient privileges to run it, but when I put it in the Application folder it tells the same thing.

The only way to execute the program without it telling that you can't is to start it from the Terminal with `sudo` (but only if you execute the python source because even with sudo the `.app` keeps telling you haven't sufficient privileges)

**Comment by peakwinter** [comment]
Hi there,

In order to build the .app and make it ask for the password itself (therefore not requiring the Terminal to use), I had to get creative. In order to make this work:
1. Create an .app file for the AppleScript file that is in this repository
2. Copy `Contents/Resources/arkOS Installer.applescript`, `Contents/Resources/applet.rsrc` and `Contents/Resources/Scripts` from this .app file into that same folder in the py2app-generated .app file
3. Copy `Contents/MacOS/applet` into that same folder in the py2app-generated .app file
4. Change the `CFBundleExecutable` key inside `Info.plist` to `applet`

I'm not aware of an easier way to do this, though there definitely might be one!

Thanks
J

**Comment by ghost** [comment]
I tried to do as you say, but afterwards it won't let me execute it because it says it could be damaged.
(also in the generated .app file for the AppleScript there is no `arkOS Installer.applescript` file).
The problem seems to show only after I edit the `Info.plist` file.

**Comment by peakwinter** [comment]
Hm, it seems to be working for me. Could you send me the exact error that it is returning so I can diagnose? Alternatively you can download the .app file [from the website](https://arkos.io/downloads) and make sure that your .app exactly matches the files and information in the original one.

**Comment by lazzurs** [comment]
Hello,

I am getting the same error about the .app being damaged.  I have downloaded the installer from the site and below is the shasum for the zip.

$ shasum arkos-install-mac.zip 
175095f07e7030106a1eae3ac09ddc0a27570881  arkos-install-mac.zip

If there is any further debug you would like me to do I would be happy to do so.

**Comment by peakwinter** [comment]
Hi there,

Unless you are compiling the package before running it, this error comes because your Security and Privacy Settings do not allow applications installed from all sources. Please make this change in your System Preferences then try again.

Thanks!

**Comment by lazzurs** [comment]
Thanks, you were correct.  Surprising error message for this problem.

**Comment by peakwinter** [comment]
Yeah unfortunately we have Apple to thank for that :/ Hopefully they will change it in an upcoming version!
