### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by peakwinter** [arkOScloud/arkos-install#7]

**Comment by Cathryne** [comment]
+1   I can help with translation to German.

**Comment by peakwinter** [comment]
Awesome! I'll try to get a framework up to collect strings soon so that we can get a head start, even if the functionality won't be ready for a little while. Stay tuned.

**Comment by Cathryne** [comment]
I will. Already done it in JSON, see https://github.com/Cathryne/prism-break/blob/master/lang/de.json, but I'd appreciate something more user-friendly ;-)

**Comment by ghost** [comment]
I can help with an Italian translation.

**Comment by ghost** [comment]
I downloaded and played around with the code a bit. I managed to setup gettext translation which is very simple and works quite well. The only problem I found right now is with strings that span multiple lines because the xgettext utility cannot automatically detect them and generate the file for translation ( a .po file). A solution to this might be to use string ids in the code and the full strings in the translation files.

## Example

This is the original code without support for translation:

``` python
label = QtGui.QLabel('Welcome to the arkOS Installer! This '
            'program will guide you through installing the arkOS image '
            'to an SD card inserted into your computer.\n\n'
            'Once you click Forward, your computer will start downloading '
            'the arkOS image from our servers in preparation for the '
            'install. Please make sure your computer is connected to the '
            'Internet before continuing.')
```

This is the code with support for translation:

``` python
label = QtGui.QLabel(_('introduction-label'))
```

And this will be found in the default (english) translation file:

```
msgid: "introduction-label"
msgstr: "Welcome to the arkOS Installer! This "
            "program will guide you through installing the arkOS image "
            "to an SD card inserted into your computer.\n\n"
        "Once you click Forward, your computer will start downloading "
        "the arkOS image from our servers in preparation for the "
            "install. Please make sure your computer is connected to the "
        "Internet before continuing."
```

At this point everyone will be able to translate the application by just copying the translation file and modifying the strings.

```
msgid: "introduction-label"
msgstr: "Benvenuti all'Installer di arkOS! Questo "
            "programma ti guiderà nel processo di installazione di arkOS "
            "su una scheda SD inserita nel tuo computer.\n\n"
            [continues...]
```

Afterwards the .po files need to be compiled to .mo format with the msgfmt utility and then distributed with the application so that it can use them.

I'm not showing you the actual code because its just a bunch of code lines that make everything work, and because this is just a proposal since I don't know if you are already working on this feature or you want to do it in another way. But if you think this is a fine way to do it I can easily fork, code the feature nicely and make a pull request.

Let me know what you think.

**Comment by peakwinter** [comment]
Hi there,

Wow thanks so much for taking a crack at this! I was definitely considering gettext but hadn't gotten around to playing with it yet. Feel free to submit a pull request with some changes (or the format that you believe works best, and I can work it through the rest of the app).

It will be much easier to implement this in the Installer then it will in Genesis, as Genesis uses plugins and will need a way to either import multiple .pos from different sources at once, or compile them all into memory at startup before reading. If you have an idea on how to do this, feel free to let me know and I can sketch out a plan for when I'm ready to set up i18n for that.

Thanks!!!

**Comment by elimisteve** [comment]
+1 Nice!

**Comment by peakwinter** [comment]
Thanks to @meaningfulnick's excellent contribution to set up the OS X version for i18n, all that is left to do is to extend this to the Linux version and update the translation server with the generated files. I should have this complete shortly.

**Comment by peakwinter** [comment]
@Cathryne the translation server is now up at https://trax.citizenweb.is if you are still able to contribute a German translation. Thanks!

**Comment by Cathryne** [comment]
I am, and luckily not the only one :-)

**Comment by Cathryne** [comment]
Ah, one thing we should discuss here: The English "you" can be translated to German both formally ("Sie") and informally ("Du"). Which one is more suitable for the target audience?

**Comment by peakwinter** [comment]
Good question. It's an installation program and the language in those is usually pretty formal, from my experience. So I would go with Sie, as long as it doesn't sound weird or _too_ formal to you. :) I think the French version uses "vous" too (or should, in any case).

**Comment by Cathryne** [comment]
OK. Most Germans also expect to be addressed formally. Du is mostly for family & friends.
